=== Exator921/Dark-My-Posh/dark-My-Posh.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Oh My Posh Theme Schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "final_space": {
      "type": "boolean"
    },
    "console_title_template": {
      "type": "string"
    },
    "secondary_prompt": {
      "type": "object",
      "properties": {
        "template": {
          "type": "string"
        },
        "foreground": {
          "type": "string"
        },
        "background": {
          "type": "string"
        }
      },
      "required": [
        "template",
        "foreground",
        "background"
      ]
    },
    "transient_prompt": {
      "type": "object",
      "properties": {
        "template": {
          "type": "string"
        },
        "foreground": {
          "type": "string"
        },
        "background": {
          "type": "string"
        }
      },
      "required": [
        "template",
        "foreground",
        "background"
      ]
    },
    "blocks": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "prompt",
              "rprompt"
            ]
          },
          "alignment": {
            "type": "string",
            "enum": [
              "left",
              "right"
            ]
          },
          "newline": {
            "type": "boolean"
          },
          "overflow": {
            "type": "string",
            "enum": [
              "hidden",
              "scroll",
              "visible"
            ]
          },
          "segments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "style": {
                  "type": "string"
                },
                "template": {
                  "type": "string"
                },
                "foreground": {
                  "type": "string"
                },
                "background": {
                  "type": "string"
                },
                "foreground_templates": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "properties": {
                  "type": "object",
                  "properties": {
                    "style": {
                      "type": "string"
                    },
                    "branch_icon": {
                      "type": "string"
                    },
                    "commit_icon": {
                      "type": "string"
                    },
                    "fetch_status": {
                      "type": "boolean"
                    },
                    "threshold": {
                      "type": "integer"
                    }
                  },
                  "additionalProperties": true
                }
              },
              "required": [
                "type",
                "style",
                "template"
              ]
            }
          }
        },
        "required": [
          "type",
          "segments"
        ]
      }
    }
  },
  "required": [
    "version",
    "blocks"
  ]
}

=== Exator921/Dark-My-Posh/.dark-My-Posh.omp.json
{
  "secondary_prompt": {
    "template": "❯❯ ",
    "foreground": "magenta",
    "background": "transparent"
  },
  "transient_prompt": {
    "template": "❯ ",
    "background": "transparent",
    "foreground": "magenta"
  },
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "properties": {
            "style": "full"
          },
          "template": "{{ if .Root }}⛯ {{ end }}{{ .Path }} {{ .Shell | upper }}",
          "foreground": "blue",
          "background": "transparent",
          "type": "path",
          "style": "plain"
        },
        {
          "properties": {
            "branch_icon": "",
            "commit_icon": "@",
            "fetch_status": true
          },
          "template": " {{ if .Detached }}┎{{ end }}{{ if .Working.Changed }}*{{ end }}{{ .HEAD }}{{ if .Staging.Changed }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ .HEAD }}{{ if gt .Ahead 0 }}⇡{{ end }}</>",
          "foreground": "p:grey",
          "background": "transparent",
          "type": "git",
          "style": "plain"
        }
      ],
      "newline": true
    },
    {
      "type": "rprompt",
      "overflow": "hidden",
      "segments": [
        {
          "properties": {
            "threshold": 5000
          },
          "template": "{{ .FormattedMs }}",
          "foreground": "yellow",
          "background": "transparent",
          "type": "executiontime",
          "style": "plain"
        }
      ]
    },
    {
  "type": "prompt",
  "alignment": "left",
  "segments": [
    {
      "template": "♦ ",
      "background": "transparent",
      "type": "text",
      "style": "plain",
      "foreground_templates": [
        "{{if gt .Code 0}}#FF0000{{else}}#800080{{end}}"
      ]
    },
    {
      "template": "❯",
      "background": "transparent",
      "type": "text",
      "style": "plain",
      "foreground": "magenta"
    }
  ],
  "newline": true
}
  ],
  "version": 3,
  "final_space": true
}
